package com.asymt.addon.integral.model;

import io.jboot.db.annotation.Table;
import com.asymt.addon.integral.model.base.BaseIntegralDetails;

/**
 * Generated by JPress.
 */
@Table(tableName = "integral_details", primaryKey = "id")
public class IntegralDetails extends BaseIntegralDetails<IntegralDetails> {

    private static final long serialVersionUID = 1L;

	
}

