package com.asymt.addon.resourcesite.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialExtend<M extends BaseMaterialExtend<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 文章ID
     */
	public void setArticleId(Long articleId) {
		set("article_id", articleId);
	}

    /**
     * 文章ID
     */
	public Long getArticleId() {
		return getLong("article_id");
	}

    /**
     * 素材来源,1：原创，2：转载
     */
	public void setSource(Integer source) {
		set("source", source);
	}

    /**
     * 素材来源,1：原创，2：转载
     */
	public Integer getSource() {
		return getInt("source");
	}

    /**
     * 下载量
     */
	public void setDownloadCount(Integer downloadCount) {
		set("download_count", downloadCount);
	}

    /**
     * 下载量
     */
	public Integer getDownloadCount() {
		return getInt("download_count");
	}

    /**
     * 素材下载地址
     */
	public void setUrl(String url) {
		set("url", url);
	}

    /**
     * 素材下载地址
     */
	public String getUrl() {
		return getStr("url");
	}

}

