package com.asymt.addon.integral.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntegralDetails<M extends BaseIntegralDetails<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
	public void setId(Integer id) {
		set("id", id);
	}

    /**
     * 主键ID
     */
	public Integer getId() {
		return getInt("id");
	}

    /**
     * 用户ID
     */
	public void setUserId(Integer userId) {
		set("user_id", userId);
	}

    /**
     * 用户ID
     */
	public Integer getUserId() {
		return getInt("user_id");
	}

    /**
     * 积分值
     */
	public void setIntegral(Integer integral) {
		set("integral", integral);
	}

    /**
     * 积分值
     */
	public Integer getIntegral() {
		return getInt("integral");
	}

    /**
     * 备注
     */
	public void setRemark(String remark) {
		set("remark", remark);
	}

    /**
     * 备注
     */
	public String getRemark() {
		return getStr("remark");
	}

    /**
     * 创建时间
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

    /**
     * 过期时间
     */
	public void setExpire(java.util.Date expire) {
		set("expire", expire);
	}

    /**
     * 过期时间
     */
	public java.util.Date getExpire() {
		return getDate("expire");
	}

    /**
     * 积分类型(1：新增积分，2：消耗积分，3：过期积分)
     */
	public void setType(Integer type) {
		set("type", type);
	}

    /**
     * 积分类型(1：新增积分，2：消耗积分，3：过期积分)
     */
	public Integer getType() {
		return getInt("type");
	}

}

