package com.asymt.addon.resourcesite.model;

import io.jboot.db.annotation.Table;
import com.asymt.addon.resourcesite.model.base.BaseIntegralAvailables;

/**
 * Generated by JPress.
 */
@Table(tableName = "integral_availables", primaryKey = "id")
public class IntegralAvailables extends BaseIntegralAvailables<IntegralAvailables> {

    private static final long serialVersionUID = 1L;

	
}

