package com.asymt.addon.resourcesite.model;

import io.jboot.db.annotation.Table;
import com.asymt.addon.resourcesite.model.base.BaseMaterialExtend;

/**
 * Generated by JPress.
 */
@Table(tableName = "material_extend")
public class MaterialExtend extends BaseMaterialExtend<MaterialExtend> {

    private static final long serialVersionUID = 1L;


}

