package com.asymt.addon.resourcesite.model;

import io.jboot.db.annotation.Table;
import com.asymt.addon.resourcesite.model.base.BaseSlide;

/**
 * Generated by JPress.
 */
@Table(tableName = "slide", primaryKey = "id")
public class Slide extends BaseSlide<Slide> {

    private static final long serialVersionUID = 1L;

	
}

